# Generated by Django 5.0.4 on 2024-08-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_comments_alter_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
