# Generated by Django 5.0.4 on 2024-07-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_address_alter_book_author_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entires'},
        ),
        migrations.AddField(
            model_name='book',
            name='country_published',
            field=models.ManyToManyField(to='books.country'),
        ),
    ]
